ALTER TABLE shop ADD COLUMN razao_social VARCHAR(255);
ALTER TABLE shop ADD COLUMN fantasia VARCHAR(255);
ALTER TABLE shop ADD COLUMN cnpj VARCHAR(14);
ALTER TABLE shop ADD COLUMN logradouro VARCHAR(255);
ALTER TABLE shop ADD COLUMN numero VARCHAR(50);
ALTER TABLE shop ADD COLUMN telefone VARCHAR(11);
ALTER TABLE shop ADD COLUMN contato VARCHAR(255);